**Machine Learning practice problems from book Machine Learning with Python Cookbook by Kyle Gallatin and Chris Albon**

# Naive Bayes

Bayes’ theorem is the premier method for understanding the probability of some
event, P A ∣ B , given some new information, P B ∣ A , and a prior belief in the
probability of the event, P A :
P (A ∣ B) = (P (B ∣ A)*P (A) )/ P (B)

## Training a Classifier for Continuous Features

In [1]:
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB
# Load data
iris = datasets.load_iris()
features = iris.data
target = iris.target
# Create Gaussian naive Bayes object
classifer = GaussianNB()
# Train model
model = classifer.fit(features, target)

In [2]:
# Create new observation
new_observation = [[ 4, 4, 4, 0.4]]
# Predict class
model.predict(new_observation)

array([1])

In [3]:
# Create Gaussian naive Bayes object with prior probabilities of each class
clf = GaussianNB(priors=[0.25, 0.25, 0.5])
# Train model
model = classifer.fit(features, target)

## Training a Classifier for Discrete and Count Features

In [4]:
import numpy as np
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import CountVectorizer
# Create text
text_data = np.array(['I love Brazil. Brazil!',
'Brazil is best',
'Germany beats both'])
# Create bag of words
count = CountVectorizer()
bag_of_words = count.fit_transform(text_data)
# Create feature matrix
features = bag_of_words.toarray()
# Create target vector
target = np.array([0,0,1])
# Create multinomial naive Bayes object with prior probabilities of each class
classifer = MultinomialNB(class_prior=[0.25, 0.5])
# Train model
model = classifer.fit(features, target)

In [5]:
# Create new observation
new_observation = [[0, 0, 0, 1, 0, 1, 0]]
# Predict new observation's class
model.predict(new_observation)

array([0])

## Training a Naive Bayes Classifier for Binary Features

In [7]:
# Load libraries
import numpy as np
from sklearn.naive_bayes import BernoulliNB
# Create three binary features
features = np.random.randint(2, size=(100, 3))
# Create a binary target vector
target = np.random.randint(2, size=(100, 1)).ravel()
# Create Bernoulli naive Bayes object with prior probabilities of each class
classifer = BernoulliNB(class_prior=[0.25, 0.5])
# Train model
model = classifer.fit(features, target)

In [8]:
model_uniform_prior = BernoulliNB(class_prior=None, fit_prior=False)

## Calibrating Predicted Probabilities

In [9]:
# Load libraries
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB
from sklearn.calibration import CalibratedClassifierCV
# Load data
iris = datasets.load_iris()
features = iris.data
target = iris.target
# Create Gaussian naive Bayes object
classifer = GaussianNB()
# Create calibrated cross-validation with sigmoid calibration
classifer_sigmoid = CalibratedClassifierCV(classifer, cv=2, method='sigmoid')
# Calibrate probabilities
classifer_sigmoid.fit(features, target)
# Create new observation
new_observation = [[ 2.6, 2.6, 2.6, 0.4]]
# View calibrated probabilities
classifer_sigmoid.predict_proba(new_observation)

array([[0.31859971, 0.63663451, 0.04476578]])

In [10]:
# Train a Gaussian naive Bayes then predict class probabilities
classifer.fit(features, target).predict_proba(new_observation)

array([[2.31548432e-04, 9.99768128e-01, 3.23532277e-07]])

# Clustering

## Clustering Using K-Means

K-means clustering is one of the most common clustering techniques. In k-means
clustering, the algorithm attempts to group observations into k groups, with each group having roughly equal variance. The number of groups, k, is specified by the
user as a hyperparameter. Specifically, in k-means:

1. k cluster “center” points are created at random locations.

2. For each observation:
a. The distance between each observation and the k center points is calculated.
b. The observation is assigned to the cluster of the nearest center point.

3. The center points are moved to the means (i.e., centers) of their respective
clusters.

4. Steps 2 and 3 are repeated until no observation changes in cluster membership.

At this point the algorithm is considered converged and stops.



In [12]:
# Load libraries
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
# Load data
iris = datasets.load_iris()
features = iris.data
# Standardize features
scaler = StandardScaler()
features_std = scaler.fit_transform(features)
# Create k-means object
cluster = KMeans(n_clusters=3, random_state=0, n_init="auto")
# Train model
model = cluster.fit(features_std)

In [13]:
# View predicted class
model.labels_

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 2, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 2,
       0, 0, 0, 0, 2, 0, 0, 0, 0, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 2, 2, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 2, 2, 2, 2, 0, 2, 2, 2,
       2, 2, 2, 0, 0, 2, 2, 2, 2, 0, 2, 0, 2, 0, 2, 2, 0, 2, 2, 2, 2, 2,
       2, 0, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 0], dtype=int32)

In [14]:
# View true class
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [15]:
# Create new observation
new_observation = [[0.8, 0.8, 0.8, 0.8]]
# Predict observation's cluster
model.predict(new_observation)

array([2], dtype=int32)

In [16]:
# View cluster centers
model.cluster_centers_

array([[-0.05021989, -0.88337647,  0.34773781,  0.2815273 ],
       [-1.01457897,  0.85326268, -1.30498732, -1.25489349],
       [ 1.13597027,  0.08842168,  0.99615451,  1.01752612]])

## Speeding Up K-Means Clustering

In [18]:
# Load libraries
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import MiniBatchKMeans
# Load data
iris = datasets.load_iris()
features = iris.data
# Standardize features
scaler = StandardScaler()
features_std = scaler.fit_transform(features)
# Create k-mean object
cluster = MiniBatchKMeans(n_clusters=3,
                          random_state=0,
                          batch_size=100,
                          n_init="auto")
# Train model
model = cluster.fit(features_std)

## Clustering Using Mean Shift

In [19]:
# Load libraries
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import MeanShift
# Load data
iris = datasets.load_iris()
features = iris.data
# Standardize features
scaler = StandardScaler()
features_std = scaler.fit_transform(features)
# Create mean shift object
cluster = MeanShift(n_jobs=-1)
# Train model
model = cluster.fit(features_std)

## Clustering Using DBSCAN

In [20]:
# Load libraries
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import DBSCAN
# Load data
iris = datasets.load_iris()
features = iris.data
# Standardize features
scaler = StandardScaler()
features_std = scaler.fit_transform(features)
# Create DBSCAN object
cluster = DBSCAN(n_jobs=-1)
# Train model
model = cluster.fit(features_std)

In [21]:
# Show cluster membership
model.labels_

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1, -1,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1, -1,
        0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  1,
        1,  1,  1,  1,  1, -1, -1,  1, -1, -1,  1, -1,  1,  1,  1,  1,  1,
       -1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
       -1,  1, -1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1, -1,  1, -1,  1,
        1,  1,  1, -1, -1, -1, -1, -1,  1,  1,  1,  1, -1,  1,  1, -1, -1,
       -1,  1,  1, -1,  1,  1, -1,  1,  1,  1, -1, -1, -1,  1,  1,  1, -1,
       -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1])

## Clustering Using Hierarchical Merging

In [ ]:
# Load libraries
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import AgglomerativeClustering
# Load data
iris = datasets.load_iris()
features = iris.data
# Standardize features
scaler = StandardScaler()
features_std = scaler.fit_transform(features)
# Create agglomerative clustering object
cluster = AgglomerativeClustering(n_clusters=3)
# Train model
model = cluster.fit(features_std)

In [22]:
# Show cluster membership
model.labels_

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1, -1,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1, -1,
        0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  1,
        1,  1,  1,  1,  1, -1, -1,  1, -1, -1,  1, -1,  1,  1,  1,  1,  1,
       -1,  1,  1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
       -1,  1, -1,  1,  1,  1,  1,  1, -1,  1,  1,  1,  1, -1,  1, -1,  1,
        1,  1,  1, -1, -1, -1, -1, -1,  1,  1,  1,  1, -1,  1,  1, -1, -1,
       -1,  1,  1, -1,  1,  1, -1,  1,  1,  1, -1, -1, -1,  1,  1,  1, -1,
       -1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, -1,  1])

# Tensors with Pytorch

In [23]:
# Load library
import torch
# Create a vector as a row
tensor_row = torch.tensor([1, 2, 3])

# Create a vector as a column
tensor_column = torch.tensor(
                              [
                              [1],
                              [2],
                              [3]
                              ]
                              )

In [25]:
tensor_row

tensor([1, 2, 3])

In [24]:
tensor_column

tensor([[1],
        [2],
        [3]])

## Creating a Tensor from NumPy

In [27]:
import numpy as np
import torch
# Create a NumPy array
vector_row = np.array([1, 2, 3])
# Create a tensor from a NumPy array
tensor_row1 = torch.from_numpy(vector_row)

In [28]:
tensor_row1

tensor([1, 2, 3])

## Creating a Sparse Tensor

In [30]:
# Import libraries
import torch
# Create a tensor
tensor = torch.tensor(
[
[0, 0],
[0, 1],
[3, 0]
]
)
# Create a sparse tensor from a regular tensor
sparse_tensor = tensor.to_sparse()

In [31]:
print(type(tensor))
print(type(sparse_tensor))

<class 'torch.Tensor'>
<class 'torch.Tensor'>


## Selecting Elements in a Tensor

In [35]:
# Load library
import torch
# Create vector tensor
vector = torch.tensor([1, 2, 3, 4, 5, 6])
# Create matrix tensor
matrix = torch.tensor(
[
[1, 2, 3],
[4, 5, 6],
[7, 8, 9]
]
)
# Select third element of vector
print(vector[2])

# Select second row, second column
print(matrix[1,1])

tensor(3)
tensor(5)


In [36]:
# Select all elements of a vector
print(vector[:])

# Select everything up to and including the third element
print(vector[:3])

tensor([1, 2, 3, 4, 5, 6])
tensor([1, 2, 3])


In [37]:
# Select the first two rows and all columns of a matrix
matrix[:2,:]

tensor([[1, 2, 3],
        [4, 5, 6]])

In [38]:
#Select all rows and the second column
matrix[:,1:2]

tensor([[2],
        [5],
        [8]])

In [42]:
# Select the last element
vector[-1]

tensor(6)

In [45]:
vector.flip(dims=(-1,))

tensor([6, 5, 4, 3, 2, 1])

In [46]:

tensor = torch.tensor([[1,2,3], [1,2,3]])
# Get the shape of the tensor
tensor.shape

torch.Size([2, 3])

In [47]:
# Get the data type of items in the tensor
tensor.dtype

torch.int64

In [48]:
# Get the layout of the tensor
tensor.layout

torch.strided

In [49]:
# Get the device being used by the tensor
tensor.device

device(type='cpu')

## Applying Operations to Elements

In [50]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
# Broadcast an arithmetic operation to all elements in a tensor
tensor * 100

tensor([100, 200, 300])

In [51]:
# Create a tensor
torch.tensor([1,2,3])
# Find the largest value
tensor.max()

tensor(3)

In [52]:
# Find the smallest value
tensor.min()

tensor(1)

In [53]:
# Create 4x3 tensor
tensor = torch.tensor([[1, 2, 3],
[4, 5, 6],
[7, 8, 9],
[10, 11, 12]])
# Reshape tensor into 2x6 tensor
tensor.reshape(2, 6)

tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])

In [54]:
# Create a two-dimensional tensor
tensor = torch.tensor([[[1,2,3]]])
# Transpose it
tensor.mT

tensor([[[1],
         [2],
         [3]]])

In [56]:
"""
An additional way to transpose PyTorch tensors of any shape is to use the permute
method:
"""
tensor.permute(*torch.arange(tensor.ndim - 1, -1, -1))

tensor([[[1]],

        [[2]],

        [[3]]])

In [57]:
tensor = torch.tensor([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
# Flatten tensor
tensor.flatten()

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
tensor_1 = torch.tensor([1, 2, 3])
# Create another tensor
tensor_2 = torch.tensor([4, 5, 6])
# Multiply the two tensors
tensor_1 * tensor_2

tensor([ 4, 10, 18])

In [60]:
tensor_1+tensor_2

tensor([5, 7, 9])

In [61]:
tensor_1-tensor_2

tensor([-3, -3, -3])

In [62]:
tensor_1/tensor_2

tensor([0.2500, 0.4000, 0.5000])

In [58]:
# Create one tensor
tensor_1 = torch.tensor([1, 2, 3])
# Create another tensor
tensor_2 = torch.tensor([4, 5, 6])
# Calculate the dot product of the two tensors
tensor_1.dot(tensor_2)

tensor(32)

# Neural Networks

In [63]:
## Using Autograd with PyTorch
# Import libraries
import torch
# Create a torch tensor that requires gradients
t = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
# Perform a tensor operation simulating "forward propagation"
tensor_sum = t.sum()
# Perform back propagation
tensor_sum.backward()
# View the gradients
t.grad

tensor([1., 1., 1.])

In [64]:
# Preprocessing Data for Neural Networks
from sklearn import preprocessing
import numpy as np
# Create feature
features = np.array([[-100.1, 3240.1],
                    [-200.2, -234.1],
                    [5000.5, 150.1],
                    [6000.6, -125.1],
                    [9000.9, -673.1]])
# Create scaler
scaler = preprocessing.StandardScaler()
# Convert to a tensor
features_standardized_tensor = torch.from_numpy(features)
# Show features
features_standardized_tensor

tensor([[-100.1000, 3240.1000],
        [-200.2000, -234.1000],
        [5000.5000,  150.1000],
        [6000.6000, -125.1000],
        [9000.9000, -673.1000]], dtype=torch.float64)

In [65]:
# Create features
torch_features = torch.tensor([[-100.1, 3240.1],
[-200.2, -234.1],
[5000.5, 150.1],
[6000.6, -125.1],
[9000.9, -673.1]], requires_grad=True)
# Compute the mean and standard deviation
mean = torch_features.mean(0, keepdim=True)
standard_deviation = torch_features.std(0, unbiased=False, keepdim=True)
# Standardize the features using the mean and standard deviation
torch_features_standardized = torch_features - mean
torch_features_standardized /= standard_deviation
# Show standardized features
torch_features_standardized

tensor([[-1.1254,  1.9643],
        [-1.1533, -0.5007],
        [ 0.2953, -0.2281],
        [ 0.5739, -0.4234],
        [ 1.4096, -0.8122]], grad_fn=<DivBackward0>)

## Designing a Neural Network

In [66]:
import torch
import torch.nn as nn
# Define a neural network
class SimpleNeuralNet(nn.Module):
  def __init__(self):
    super(SimpleNeuralNet, self).__init__()
    self.fc1 = nn.Linear(10, 16)
    self.fc2 = nn.Linear(16, 16)
    self.fc3 = nn.Linear(16, 1)
  def forward(self, x):
    x = nn.functional.relu(self.fc1(x))
    x = nn.functional.relu(self.fc2(x))
    x = nn.functional.sigmoid(self.fc3(x))
    return x
# Initialize the neural network
network = SimpleNeuralNet()
# Define loss function, optimizer
loss_criterion = nn.BCELoss()
optimizer = torch.optim.RMSprop(network.parameters())
# Show the network
network

SimpleNeuralNet(
  (fc1): Linear(in_features=10, out_features=16, bias=True)
  (fc2): Linear(in_features=16, out_features=16, bias=True)
  (fc3): Linear(in_features=16, out_features=1, bias=True)
)

In [67]:
# Import libraries
import torch
# Define a neural network using `Sequential`
class SimpleNeuralNet(nn.Module):
  def __init__(self):
    super(SimpleNeuralNet, self).__init__()
    self.sequential = torch.nn.Sequential(
    torch.nn.Linear(10, 16),
    torch.nn.ReLU(),
    torch.nn.Linear(16,16),
    torch.nn.ReLU(),
    torch.nn.Linear(16, 1),
    torch.nn.Sigmoid()
    )
  def forward(self, x):
    x = self.sequential(x)
    return x
# Instantiate and view the network
SimpleNeuralNet()

SimpleNeuralNet(
  (sequential): Sequential(
    (0): Linear(in_features=10, out_features=16, bias=True)
    (1): ReLU()
    (2): Linear(in_features=16, out_features=16, bias=True)
    (3): ReLU()
    (4): Linear(in_features=16, out_features=1, bias=True)
    (5): Sigmoid()
  )
)

## Training a Binary Classifier

In [79]:
# Import libraries
import torch
import torch.nn as nn
import numpy as np
from torch.utils.data import DataLoader, TensorDataset
from torch.optim import RMSprop
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
# Create training and test sets
features, target = make_classification(n_classes=2,
                                       n_features=10,
                                        n_samples=1000)
features_train, features_test, target_train, target_test = train_test_split(
features, target, test_size=0.1, random_state=1)
# Set random seed
torch.manual_seed(0)
np.random.seed(0)
# Convert data to PyTorch tensors
x_train = torch.from_numpy(features_train).float()
y_train = torch.from_numpy(target_train).float().view(-1, 1)
x_test = torch.from_numpy(features_test).float()
y_test = torch.from_numpy(target_test).float().view(-1, 1)

# Define a neural network using `Sequential`
class SimpleNeuralNet(nn.Module):
  def __init__(self):
    super(SimpleNeuralNet, self).__init__()
    self.sequential = torch.nn.Sequential(
    torch.nn.Linear(10, 16),
    torch.nn.ReLU(),
    torch.nn.Linear(16,16),
    torch.nn.ReLU(),
    torch.nn.Linear(16, 1),
    torch.nn.Sigmoid()
    )

  def forward(self, x):
    x = self.sequential(x)
    return x

# Initialize neural network
network = SimpleNeuralNet()
# Define loss function, optimizer
criterion = nn.BCELoss()
optimizer = RMSprop(network.parameters())
# Define data loader
train_data = TensorDataset(x_train, y_train)
train_loader = DataLoader(train_data, batch_size=100, shuffle=True)
# Compile the model using torch 2.0's optimizer
network = torch.compile(network)
# Train neural network
epochs = 3
for epoch in range(epochs):
    for batch_idx, (data, target) in enumerate(train_loader):
      optimizer.zero_grad()
      output = network(data)
      loss = criterion(output, target)
      loss.backward()
      optimizer.step()
print("Epoch:", epoch+1, "\tLoss:", loss.item())
# Evaluate neural network
with torch.no_grad():
  output = network(x_test)
  test_loss = criterion(output, y_test)
  test_accuracy = (output.round() == y_test).float().mean()
  print("Test Loss:", test_loss.item(), "\tTest Accuracy:",test_accuracy.item())

No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'


Epoch: 3 	Loss: 0.03935524821281433
Test Loss: 0.06877756863832474 	Test Accuracy: 0.9700000286102295
